### ISSUE TITLE
android.view.InflateException: Binary XML file line #20: Error inflating class ImageView

### ISSUE THREAD

**Issue by WangGuox1n** [Adonai/Man-Man#19]
I'm using version 1.7.1, when running app, click CONTENTS -> System Calls, then the App crash.
STACK_TRACE= E/AndroidRuntime(32210): FATAL EXCEPTION: main
E/AndroidRuntime(32210): Process: com.adonai.manman, PID: 32210
E/AndroidRuntime(32210): android.view.InflateException: Binary XML file line #20: Error inflating class ImageView
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(32210): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(32210): 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
E/AndroidRuntime(32210): 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
E/AndroidRuntime(32210): 	at com.adonai.manman.adapters.ChapterContentsArrayAdapter.getView(Unknown Source)
E/AndroidRuntime(32210): 	at android.widget.AbsListView.obtainView(AbsListView.java:2255)
E/AndroidRuntime(32210): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
E/AndroidRuntime(32210): 	at android.widget.ListView.fillDown(ListView.java:691)
E/AndroidRuntime(32210): 	at android.widget.ListView.fillFromTop(ListView.java:752)
E/AndroidRuntime(32210): 	at android.widget.ListView.layoutChildren(ListView.java:1630)
E/AndroidRuntime(32210): 	at android.widget.AbsListView.onLayout(AbsListView.java:2087)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.support.v4.view.ViewPager.onLayout(Unknown Source)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
E/AndroidRuntime(32210): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(32210): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(32210): 	at android.view.View.layout(View.java:14817)
E/AndroidRuntime(32210): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime(32210): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
E/AndroidRuntime(32210): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
E/AndroidRuntime(32210): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
E/AndroidRuntime(32210): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRoot

**Comment by Adonai** [comment]
Most probably, yes. Need info on phone and Android version you are using.

**Comment by WangGuox1n** [comment]
I'm using Genymotion device Custom phone, Android version is 4.4, API19. 



---Original---

**Comment by Adonai** [comment]
I'll take a look, thanks for the report

**Comment by Kaned1as** [comment]
Cannot reproduce, please re-test on 2.2.0 or higher
