### ISSUE TITLE
crash after clear cache

### ISSUE THREAD

**Issue by anlalalu** [Adonai/Man-Man#20]
###### Reproduction Steps

1. tap 'more options'
2. tap 'settings'
3. tap 'clear cache'
4. tap 'ok'
5. tap delete downloaded local archive
6. exit the app (kill the process in background)
7. start the app again
8. tap 'content'

###### Expected Result

Go to content interface without any error.

###### Actual Result

Crash with the stack trace: 
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.adonai.manman.debug, PID: 2091
                                                 java.lang.NullPointerException
                                                     at com.adonai.manman.ManChaptersFragment.onResume(ManChaptersFragment.java:449)
                                                     at com.adonai.manman.MainPagerActivity$ManFragmentPagerAdapter.setPrimaryItem(MainPagerActivity.java:151)
                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1266)
                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
                                                     at com.astuetz.PagerSlidingTabStrip$1.onClick(PagerSlidingTabStrip.java:258)
                                                     at android.view.View.performClick(View.java:4438)
                                                     at android.view.View$PerformClick.run(View.java:18422)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 1.7.1

Android Version = 4.4.4

**Comment by anlalalu** [comment]
Similar operations may lead to stack trace like this:

E/AndroidRuntime(16685): FATAL EXCEPTION: main
E/AndroidRuntime(16685): Process: com.adonai.manman, PID: 16685
E/AndroidRuntime(16685): java.lang.NullPointerException
E/AndroidRuntime(16685): 	at com.adonai.manman.ManChaptersFragment.onResume(Unknown Source)
E/AndroidRuntime(16685): 	at com.adonai.manman.MainPagerActivity$ManFragmentPagerAdapter.setPrimaryItem(Unknown Source)
E/AndroidRuntime(16685): 	at android.support.v4.view.ViewPager.a(Unknown Source)
E/AndroidRuntime(16685): 	at android.support.v4.view.ViewPager.a(Unknown Source)
E/AndroidRuntime(16685): 	at android.support.v4.view.ViewPager.a(Unknown Source)
E/AndroidRuntime(16685): 	at android.support.v4.view.ViewPager.setCurrentItem(Unknown Source)
E/AndroidRuntime(16685): 	at com.astuetz.PagerSlidingTabStrip$1.onClick(Unknown Source)
E/AndroidRuntime(16685): 	at android.view.View.performClick(View.java:4438)
E/AndroidRuntime(16685): 	at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime(16685): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(16685): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16685): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(16685): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(16685): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16685): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16685): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(16685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(16685): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by anlalalu** [comment]
@Adonai Do you consider this as a defect?

**Comment by Adonai** [comment]
Yes, but no time on my hands to fix it atm.

**Comment by Kaned1as** [comment]
Can't reproduce, could you please try doing this on 2.2.0 or newer?
